swagger: "2.0"
info:
  description: "This is the API documentation for CheapCheep"
  version: "1.0.0"
  title: "CheapCheep"
host: "localhost:3000"
basePath: "/api"
tags:
- name: "discount"
  description: "Discount endpoints"
- name: "rating"
  description: "Rating endpoints"
- name: "user"
  description: "User endpoints"
- name: "auth"
  description: "Authentication endpoints"
- name: "student"
  description: "Use must have an user account to access this endpoint"
- name: "business"
  description: "Use must have an business account to access this endpoint"
- name: "admin"
  description: "Use must have an admin account to access this endpoint"
- name: "public"
  description: "Endpoints that can be accessed by the public"
- name: "coming soon"
  description: "Operations not yet implemented"
schemes:
- "http"
paths:
  /discounts:
    get:
      tags:
      - "discount"
      - "public"
      summary: "Get all discounts"
      operationId: "getDiscounts"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "startAt"
        in: "query"
        type: "integer"
        required: false
      - name: "max"
        description: "max number of results to return"
        in: "query"
        type: "integer"
        required: false
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ListOfDiscounts"
        500:
          description: "Internal server error"
    post:
      tags:
      - "discount"
      - "business"
      - "admin"
      summary: "Add a new discount to the website"
      operationId: "addDiscount"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Discount object to be added"
        required: true
        schema:
          $ref: "#/definitions/DiscountReq"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/DiscountRes"
        500:
          description: "Internal server error"
  /discounts/search:
    get:
      tags:
      - "discount"
      - "public"
      summary: "Get all discounts per search criteria"
      operationId: "getDiscountsByQuery"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "query"
        in: "query"
        type: "string"
        required: false
      - name: "startAt"
        in: "query"
        type: "integer"
        required: false
      - name: "max"
        description: "max number of results to return"
        in: "query"
        type: "integer"
        required: false
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ListOfDiscounts"
        500:
          description: "Internal server error"
  /discount/{discountId}:
    get:
      tags:
      - "discount"
      - "public"
      summary: "Find discount by id"
      operationId: "getDiscountById"
      produces:
      - "application/json"
      parameters:
      - name: "discountId"
        in: "path"
        description: "Id of discount"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/DiscountRes"
        400:
          description: "Invalid id supplied"
        404:
          description: "Discount not found"
        500:
          description: "Internal server error"
    put:
      tags:
      - "discount"
      - "business"
      - "admin"
      summary: "Find discount by id"
      operationId: "editDiscountById"
      produces:
      - "application/json"
      parameters:
      - name: "discountId"
        in: "path"
        description: "Id of discount"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "Discount object to be edited"
        required: true
        schema:
          $ref: "#/definitions/DiscountReq"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/DiscountRes"
        400:
          description: "Invalid id supplied"
        404:
          description: "Discount not found"
        500:
          description: "Internal server error"
    delete:
      tags:
      - "discount"
      - "business"
      - "admin"
      summary: "Find discount by id"
      operationId: "deleteDiscountById"
      produces:
      - "application/json"
      parameters:
      - name: "discountId"
        in: "path"
        description: "Id of discount"
        required: true
        type: "integer"
      responses:
        204:
          description: "successful operation"
        400:
          description: "Invalid id supplied"
        404:
          description: "Discount not found"
        500:
          description: "Internal server error"
  /discounts/{discountId}/ratings:
    get:
      tags:
      - "discount"
      - "rating"
      summary: "Find comments on a discount by id"
      operationId: "getDiscountComments"
      produces:
      - "application/json"
      parameters:
      - name: "discountId"
        in: "path"
        description: "Id of discount"
        required: true
        type: "integer"
      - name: "startAt"
        in: "query"
        type: "integer"
        required: false
      - name: "max"
        description: "max number of results to return"
        in: "query"
        type: "integer"
        required: false
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ListOfRatings"
        500:
          description: "Internal server error"
    post:
      tags:
      - "discount"
      - "rating"
      summary: "Create a rating on a discount by id"
      operationId: "createDiscountComment"
      produces:
      - "application/json"
      parameters:
      - name: "discountId"
        in: "path"
        description: "Id of discount"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "Comment object to be added"
        required: true
        schema:
          $ref: "#/definitions/RatingReq"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/RatingRes"
        400:
          description: "Invalid id supplied"
        404:
          description: "Discount not found"
        500:
          description: "Internal server error"
  /users:
    get:
      tags:
      - "user"
      - "admin"
      summary: "Get all user"
      operationId: "getUsers"
      produces:
      - "application/json"
      parameters:
      - name: "startAt"
        in: "query"
        type: "integer"
        required: false
      - name: "max"
        description: "max number of results to return"
        in: "query"
        type: "integer"
        required: false
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ListOfUsers"
        500:
          description: "Internal server error"
  /users/search:
    get:
      tags:
      - "user"
      - "admin"
      summary: "Get all users per search criteria"
      operationId: "getUsersByQuery"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "query"
        in: "query"
        type: "string"
        required: false
      - name: "startAt"
        in: "query"
        type: "integer"
        required: false
      - name: "max"
        description: "max number of results to return"
        in: "query"
        type: "integer"
        required: false
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ListOfUsers"
        500:
          description: "Internal server error"
  /users/{userId}:
    get:
      tags:
      - "user"
      - "admin"
      summary: "Find user by id"
      operationId: "getUserById"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "Id of user"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid id supplied"
        404:
          description: "User not found"
        500:
          description: "Internal server error"
    delete:
      tags:
      - "user"
      - "admin"
      summary: "Delete user by id"
      operationId: "deleteUserById"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "Id of user"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid id supplied"
        404:
          description: "User not found"
        500:
          description: "Internal server error"
  /auth/login:
    post:
      tags:
      - "auth"
      - "public"
      summary: "Logs user into the system"
      operationId: "login"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object"
        required: true
        schema:
          $ref: "#/definitions/Login"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid username/password supplied"
  /auth/signup:
    post:
      tags:
      - "auth"
      - "public"
      summary: "Logs user into the system"
      operationId: "signup"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object"
        required: true
        schema:
          $ref: "#/definitions/Signup"
      responses:
        201:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid username/password supplied"
  /auth/logout:
    get:
      tags:
      - "auth"
      - "public"
      summary: "Logs out current logged in user session"
      operationId: "logout"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Successful operation"
        500:
          description: "Internal server error"
definitions:
  ListOfUsers:
    type: "object"
    properties:
      startAt:
        type: "integer"
        description: "Start index of search"
      total:
        type: "integer"
        description: "Total results in db"
      max:
        type: "integer"
        description: "Results returned"
      discounts:
        type: "array"
        description: "Users for current page"
        items:
          $ref: "#/definitions/User"
  Login:
    type: "object"
    required:
    - "username"
    - "password"
    properties:
      username:
        type: "string"
        example: "admin"
      password:
        type: "string"
  Signup:
    type: "object"
    required:
    - "email"
    - "password"
    - "username"
    - "accountType"
    properties:
      email:
        type: "string"
        example: "admin@cheapcheep.life"
      password:
        type: "string"
      username:
        type: "string"
        example: "admin"
      accountType:
        type: "string"
        description: "account type"
        enum:
        - "student"
        - "business"
        - "admin"
      businessName:
        type: "string"
        example: "Cheap Cheep"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      email:
        type: "string"
        example: "admin@cheapcheep.life"
      username:
        type: "string"
        example: "admin"
      accountType:
        type: "string"
        description: "account type"
        enum:
        - "student"
        - "business"
        - "admin"
      businessName:
        type: "string"
        example: "Cheap Cheep"
  ListOfDiscounts:
    type: "object"
    properties:
      startAt:
        type: "integer"
        description: "Start index of search"
      total:
        type: "integer"
        description: "Total results in db"
      max:
        type: "integer"
        description: "Results returned"
      discounts:
        type: "array"
        description: "Discounts for current page"
        items:
          $ref: "#/definitions/DiscountRes"
  DiscountReq:
    type: "object"
    required:
    - "title"
    - "isOnline"
    - "isInPerson"
    - "isCoupon"
    properties:
      title:
        type: "string"
        example: "$0.50 Off Banh Mi"
      discount:
        type: "string"
        example: "$0.50 off"
      isOnline:
        type: "boolean"
      isInPerson:
        type: "boolean"
      isCoupon:
        type: "boolean"
      start: 
        type: "string"
        format: "date"
      end:
        type: "string"
        format: "date"
      url:
        type: "string"
        example: "http://www.cheapcheep.life"
      address:
        type: "string"
        example: "123 Fake Street Sydney NSW 2000"
      lat:
        type: "integer"
      long:
        type: "integer"
      couponCodes:
        type: "string"
        example: "ABC123"
      description:
        type: "string"
        example: "Present your valid student card to receive $0.50 off 1 roll."
      finePrint:
        type: "string"
        example: "Valid for 1 roll per day."
      status:
        type: "string"
        description: "Discount status"
        enum:
        - "active"
        - "inactive"
      category:
        type: "string"
        example: "Food"
  DiscountRes:
    type: "object"
    properties:
      id:
        type: "integer"
      creatorId:
        type: "string"
      title:
        type: "string"
        example: "$0.50 Off Banh Mi"
      discount:
        type: "string"
        example: "$0.50 off"
      isOnline:
        type: "boolean"
      isInPerson:
        type: "boolean"
      isCoupon:
        type: "boolean"
      start: 
        type: "string"
        format: "date"
      end:
        type: "string"
        format: "date"
      url:
        type: "string"
        example: "http://www.cheapcheep.life"
      address:
        type: "string"
        example: "123 Fake Street Sydney NSW 2000"
      lat:
        type: "integer"
      long:
        type: "integer"
      couponCodes:
        type: "string"
        example: "ABC123"
      description:
        type: "string"
        example: "Present your valid student card to receive $0.50 off 1 roll."
      finePrint:
        type: "string"
        example: "Valid for 1 roll per day."
      status:
        type: "string"
        description: "Discount status"
        enum:
        - "active"
        - "inactive"
      category:
        type: "string"
        example: "Food"
  ListOfRatings:
    type: "object"
    properties:
      startAt:
        type: "integer"
        description: "Start index of search"
      total:
        type: "integer"
        description: "Total results in db"
      max:
        type: "integer"
        description: "Results returned"
      discounts:
        type: "array"
        description: "Ratings for current page"
        items:
          $ref: "#/definitions/RatingRes"
  RatingReq:
    type: "object"
    properties:
      discountId:
        type: "integer"
      rating:
        type: "integer"
      comment:
        type: "string"
  RatingRes:
    type: "object"
    properties:
      id:
        type: "integer"
      discountId:
        type: "integer"
      userId:
        type: "integer"
      rating:
        type: "integer"
      comment:
        type: "string"
        